spring:
  application:
    name: poctime

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/poctime-app
          jwk-set-uri: http://localhost:9090/realms/poctime-app/protocol/openid-connect/certs

  data:
    redis:
      host: localhost
      port: 6379

  datasource:
    url: jdbc:postgresql://localhost:5432/poctime
    username: admin
    password: admin@123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: app.mkiniz.poctime.shared.repository.PostgreSQLDialectCustom
        format_sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin@123
    virtual-host: poctime

server:
  port: 8181

logging:
  level:
    root: INFO
    app.mkiniz.poctime.base.tax.ncm: DEBUG
    org.springframework.amqp.rabbit.core.RabbitAdmin: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.results.bind: TRACE


rabbitmq:
  dlx-exchange: dlx.poctime
  dlx-queue: dlx.poctime.queue
  dlx-routing-key: poctime.error

poctime:
  ncm:
    url: https://portalunico.siscomex.gov.br/classif/api/publico/nomenclatura/download/json?perfil=PUBLICO
    tenant: 0px7wdx2f3dh0
    timeoutInSeconds: 18000

kind: Application